name: 'HostLoc-Points'
 
on:
  #push:
  schedule:
    # UTC (国内 UTC+8)
     - cron: '57 1 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
        - name: 'Checkout codes'
          uses: actions/checkout@v2
#         - name: 'Set up Python'
#           uses: actions/setup-python@v2
#           with:
#             python-version: '3.9.10'

        - name: 'Install requirements'
          run: |
            python3 -m pip install -r ./requirements.txt
#            python3 -m pip install --upgrade pip
        - name: 'SignIn'
          env:
            HOSTLOC_USERNAME: ${{ secrets.HOSTLOC_USERNAME }}
            HOSTLOC_PASSWORD: ${{ secrets.HOSTLOC_PASSWORD }}
            BARK_KEY: ${{ secrets.BARK_KEY }}
            TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
            TG_USER_ID: ${{ secrets.TG_USER_ID }}
            
          run: |
            python3 ./main.py
