name: 'HostLoc-Points'
 
on:
  #push:
  schedule:
    # UTC (国内 UTC+8)
     - cron: '21 1 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
        - name: 'Checkout codes'
          uses: actions/checkout@v3
#         - name: 'Set up Python'
#           uses: actions/setup-python@v2
#           with:
#             python-version: '3.9.10'

        - name: 'Delete workflow runs'
          uses: MajorScruffy/delete-old-workflow-runs@v0.3.0
          with:
            repository: ${{ github.repository }}   # replace this with your own repository such as >> owner/repo
            older-than-seconds: 172800          # remove all workflow runs older than 1 day >> 24*60*60=86400
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        - name: 'Install requirements'
          run: |
            python3 -m pip install -r ./requirements.txt
#            python3 -m pip install --upgrade pip
        - name: 'SignIn'
          env:
            HOSTLOC_USERNAME: ${{ secrets.HOSTLOC_USERNAME }}
            HOSTLOC_PASSWORD: ${{ secrets.HOSTLOC_PASSWORD }}
            BARK_KEY: ${{ secrets.BARK_KEY }}
            TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
            TG_USER_ID: ${{ secrets.TG_USER_ID }}
            
          run: |
            python3 ./main.py
